import{a as P,S as w,i as l}from"./assets/vendor-550cebad.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();let S=15;async function x(){n===1?u.elements.search.value.trim().split(" ").join("+"):g.trim().split(" ").join("+");const e=new URLSearchParams({key:"43014470-46919859f304ff208235eaa47",q:searchImgs,image_type:"photo",orientation:"horizontal",safesearch:"true"});return(await P.get(`https://pixabay.com/api/?${e}`)).data}const h=document.querySelector(".gallery"),O=new w(".gallery a",{captionsData:"alt",captionDelay:250});function $(e){const s=e.map(({largeImageURL:r,webformatURL:a,tags:t,likes:o,views:i,comments:b,downloads:L})=>`<li class="photos-list-item">
            <a class="photos-list-link" href="${r}">
            <img class="photo" src="${a}" alt="${t}"/>
            </a>
            <ul class="photo-information-container">
            <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${o}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${i}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${b}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${L}</p></li>
            </ul>
            </li>`).join("");h.insertAdjacentHTML("beforeend",s),O.refresh()}const u=document.querySelector(".search-form");let n=1,g="";const c=document.querySelector(".next-page-btn");p(c);const d=document.querySelector(".loader");p(d);let m=1;window.onload=F;u.addEventListener("submit",q);c.addEventListener("click",v);function q(e){e.preventDefault(),h.innerHTML="";const s=e.target.elements.search.value.trim();if(s!=="")n=1,g=s,y();else return l.show({message:"Please complete the field!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})}async function y(){try{if(p(c),f(d),n<=m){const e=await x();if(e.totalHits!=0){m=Math.ceil(e.totalHits/S),$(e.hits);const r=h.querySelector(".photos-list-item").getBoundingClientRect();window.scrollBy({top:r.height*2,behavior:"smooth"}),n<m?f(c):l.info({theme:"dark",progressBarColor:"#FFFFFF",position:"topRight",message:"We're sorry, there are no more images to load"})}else l.error({message:"Sorry, there are no images matching your search query. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})}}catch(e){console.log(e),l.error({message:`${e.message}`,theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})}finally{p(d),F(),u.reset()}}function v(){++n,y()}function f(e){e.classList.toggle("hidden"),e.style.display="flex"}function p(e){e.classList.toggle("hidden"),e.style.display="none"}function F(){document.body.classList.add("loaded"),document.body.classList.remove("loaded_hiding")}
//# sourceMappingURL=commonHelpers.js.map
